resolver 127.0.0.11;

upstream frontend_upstream {
    server frontend1:80;
    server frontend2:80;
}

server {
    listen 80;
    server_name app.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name app.local;

    ssl_certificate /etc/nginx/certs/app.local.crt;
    ssl_certificate_key /etc/nginx/certs/app.local.key;

    location /api/ {
        proxy_pass http://kanban-app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
    }

    location / {
        proxy_pass http://frontend_upstream;
    }
}